### PR TITLE
Build improvements

### LINKED ISSUE #62: Report versioning
We should add a version field to the json report, so that bugs can be traced back to the corresponding commit.

A way to do it would be to somehow insert the Git commit in the build process, so that it is then used when a report is produced.

### LINKED ISSUE #83: Add Soufflé binaries to .jar
Currently the binaries generated in the build/ folder have to be copied along with the .jar. It would be better to just have everything runnable via the .jar.

### PR DESCRIPTION
**Pull request by hiqua**
Closes #83.
Closes #62.

### CODE REVIEW

**Comment by ritzdorf** [comment]
> > LGTM.
> > Is the version supposed to appear somewhere in the output?
> 
> Yes, with `--json`.

Thanks. That is what I expected, but it somehow didn't happen. Let me rebuild again.

**Comment by ritzdorf** [comment]
The reason was that I was still running the old commands. Should we update the README to say `securify.jar` instead of `securify-0.1.jar`?

**Comment by hiqua** [comment]
> The reason was that I was still running the old commands. Should we update the README to say `securify.jar` instead of `securify-0.1.jar`?

Ah yes it's not so nice that we can now end up with two .jar. I think having securify.jar as a default filename is better, and we then don't have to update the documentation, and it gets overwritten properly when we rebuild.

**Comment by ritzdorf** [comment]
Not sure if it is as a result of this PR, but 
```
java -jar build/libs/securify.jar -fh src/test/resources/solidity/transaction-reordering.bin.hex --json -o /tmp/test.json
```
seems to produce no output for me. 
Is this expected?

**Comment by hiqua** [comment]
> Not sure if it is as a result of this PR, but
> 
> ```
> java -jar build/libs/securify.jar -fh src/test/resources/solidity/transaction-reordering.bin.hex --json -o /tmp/test.json
> ```
> 
> seems to produce no output for me.
> Is this expected?

`--json` was never made compatible with `-fh`, I can add checks in the argument parser to prevent this from failing silently.

**Comment by ritzdorf** [comment]
> > Not sure if it is as a result of this PR, but
> > ```
> > java -jar build/libs/securify.jar -fh src/test/resources/solidity/transaction-reordering.bin.hex --json -o /tmp/test.json
> > ```
> > seems to produce no output for me.
> > Is this expected?
> 
> `--json` was never made compatible with `-fh`, I can add checks in the argument parser to prevent this from failing silently.

Just asking because:
```
java -jar build/libs/securify.jar -fh src/test/resources/solidity/transaction-reordering.bin.hex
```
(as it is in the README) seems to generate no output or result.

**Comment by hiqua** [comment]
Yes it's only stored in some temporary file in this case. I'll just output its content instead.

**Comment by ritzdorf** [comment]
> Yes it's only stored in some temporary file in this case. I'll just output its content instead.

I was just wondering what the expected output of that `README` command is, because at the moment it doesn't do anything.

**Pull request closed without merging**
